### ISSUE TITLE
Please pick the version you prefer for Rocq 9.0 in Rocq Platform 2025.09

### ISSUE THREAD

**Issue by Justme0606** [lukaszcz/coqhammer#193]
The Rocq team released Rocq `9.0.0` on March 12th, 2025.
The corresponding Rocq Platform release `2025.09` should be released before **Oct 24th, 2025**.
It can be delayed in case of difficulties until Nov 21st, 2025, but this should be an exception.

This issue is to inform you that the opam package we are currently testing in Rocq Platform CI **works fine** with Rocq `9.0.0`.

Rocq Platform CI is currently testing opam package `coq-hammer-tactics.1.3.2+8.20`
from platform patch repository https://github.com/rocq-prover/platform/tree/main/opam/opam-coq-archive/released/packages/coq-hammer-tactics/coq-hammer-tactics.1.3.2+8.20/opam.  **This means we had to weaken some version restrictions in the opam package, but no other changes were required.**

**In case this is the version you want to see in Rocq Platform, there is nothing to do for you - please just close this issue.**

In case you would prefer to see an updated or an older version in the upcoming Rocq Platform `2025.09`, please inform us as soon as possible and before **Sep 26th, 2025**!

The working branch of Rocq Platform, can be found here [main](https://github.com/rocq-prover/platform/tree/main).
It contains package pick [`~9.0+preview~2025.08`](https://github.com/rocq-prover/platform/tree/main/package_picks/package-pick-9.0+preview~2025.08.sh) which already supports Rocq version `9.0.0` and contains already working (possibly patched / commit pinned) Rocq Platform packages.

In case you want to select a different version, please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Rocq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Rocq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/rocq-prover/platform/issues/481

**Comment by lukaszcz** [comment]
Currently, I have a problem compiling the project with Rocq 9.0 which I didn't manage to fix quickly. It may take some time before I figure this out.

**Comment by lukaszcz** [comment]
The release `v1.3.2-rocq9.0` on tag `v1.3.2+9.0` works with Rocq 9.0

**Comment by Justme0606** [comment]
Hi, 
I tested the last version with Rocq 9.0 but i had an error and not updated coq-hammer without coq-hammer-tactics.

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved coq-hammer-tactics.1.3.2+9.0  (cached)
[ERROR] The compilation of coq-hammer-tactics.1.3.2+9.0 failed at "make -j16 tactics".

```
#=== ERROR while compiling coq-hammer-tactics.1.3.2+9.0 =======================#
# context              2.1.2 | linux/x86_64 | ocaml-option-flambda.1 ocaml-variants.4.14.2+options | https://coq.inria.fr/opam/released#2025-10-16 06:21
# path                 ~/.opam/CP.2025.01.0~9.0+preview~2025.08/.opam-switch/build/coq-hammer-tactics.1.3.2+9.0
# command              /usr/bin/make -j16 tactics
# exit-code            2
# env-file             ~/.opam/log/coq-hammer-tactics-2500962-84fcee.env
# output-file          ~/.opam/log/coq-hammer-tactics-2500962-84fcee.out
### output ###
# [...]
# ROCQ compile theories/Tactics/Tactics.v
# CAMLOPT -c -for-pack Hammer_lib src/lib/g_hammer_lib.ml
# File "./theories/Tactics/Tactics.v", line 6, characters 0-43:
# Error:
# System error: "src/tactics/./../lib/hammer_lib.cmxs: No such file or directory"
# 
# make[2]: *** [Makefile.coq.tactics:818 : theories/Tactics/Tactics.vo] Erreur 1
# make[2]: *** [theories/Tactics/Tactics.vo] Suppression du fichier « theories/Tactics/Tactics.glob »
# make[2]: *** Attente des tâches non terminées....
# make[1]: *** [Makefile.coq.tactics:416 : all] Erreur 2
# make[1] : on quitte le répertoire « /home/sylvain/.opam/CP.2025.01.0~9.0+preview~2025.08/.opam-switch/build/coq-hammer-tactics.1.3.2+9.0 »
# make: *** [Makefile:12 : tactics] Erreur 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build coq-hammer-tactics 1.3.2+9.0
└─ 
```

If you have time to check ? 
Best regards,

**Comment by lukaszcz** [comment]
I'm not sure what you're doing exactly. I don't have a problem. I just tried to install `coq-hammer` with `opam install coq-hammer` with rocq 9.0 in the opam switch and it worked. I got `coq-hammer-tactics.1.3.2+9.0` and `coq-hammer.1.3.2+9.0` installed with no issues.

Yes, `coq-hammer` depends on `coq-hammer-tactics`, if that's the issue. It's an explicit dependency - you can't install `coq-hammer` without installing `coq-hammer-tactics` first, but this is resolved automatically when installing with `opam install`.

**Comment by Justme0606** [comment]
Understood. I had to remove coq-hammer-tactics and coq-hammer. After rebuilding the platform, everything works. Prior to that, I was still encountering the same error. Thanks!

**Comment by Justme0606** [comment]
Hi,
Sorry to bother you again but unfortunately, i run the CI with the two updated version 1.3.2+9.0 of coq-hammer and coq-hammer-tactics and i had en error on the smoke test.
It's juste to inform you, but if you have an idea i take it ! :)
Best regards, 
```
====================== Running test file coq-hammer/test_eprover.v ======================
coqc  test_eprover.v
Deprecated environment variable COQLIB, use ROCQLIB instead.
Warning: Deprecated environment variable COQLIB, use ROCQLIB instead.
[deprecated-coq-env-var,deprecated-since-9.0,deprecated,default]
File "./test_eprover.v", line 4, characters 15-20:
Warning: Loading Stdlib without prefix is deprecated.
Use "From Stdlib Require Arith" or the deprecated "From Coq Require Arith"
for compatibility with older Coq versions.
[deprecated-missing-stdlib,deprecated-since-9.0,deprecated,default]
Detecting provers...
Eprover found
sh: vampire: command not found
Vampire not found
Z3 found
sh: cvc4: command not found
CVC4 not found
Extracting features...
Running dependency prediction (knn-1024)...
Translating the problem to FOL...
Running Z3...
Z3 succeeded
- dependencies: Stdlib.Arith.PeanoNat.Nat.lt_0_2
- definitions: Corelib.Init.Peano.lt
Reconstructing the proof...
Tactic sfirstorder succeeded.
Replace the hammer tactic with:
	sfirstorder use: Nat.lt_0_2 unfold: lt.
Extracting features...
Running dependency prediction (knn-[1024](https://github.com/rocq-prover/platform/actions/runs/18744359990/job/53478428088#step:7:1025))...
Translating the problem to FOL...
Running EProver...
EProver failed
Finished failing transaction in 20.805 secs (0.289u,0.033s) (failure)
File "./test_eprover.v", line 30, characters 7-13:
Error: Hammer failed: ATPs failed to find a proof
```

**Comment by lukaszcz** [comment]
What is this `test_eprover.v`? It's not from the CoqHammer repository, I didn't write it.

**Comment by lukaszcz** [comment]
In any case, external ATP prover tests are flaky by necessity. It may well happen that a test which worked with a previous version of Coq / CoqHammer / EProver suddenly stops working because of some small changes in proof search or premise selection (e.g. due to different identifiers available), or just different system load. Only the final reconstruction tactics are guaranteed to have reproducible results, not the `hammer` tactic.

That's why CoqHammer's CI does not include external ATP prover tests: it only runs `make quicktest` for which the `hammer` tactic can do without external ATPs. It doesn't run the full test suite with `make test`.

But it seems you're referring to some other CI tests which I didn't set up.

**Comment by Justme0606** [comment]
Hi
Thanks a lot for your answer. I understand.
I’ll try to investigate and understand the issue and how to fix it.
I’ve asked Michael to help me with this matter — my knowledge on the topic is unfortunately not at the same level as yours or Michael’s.
Best regards,

**Comment by lukaszcz** [comment]
The easiest way to fix this is to edit the test and remove the lemma with the offending `hammer` tactic.
